repos:

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        name: markdown linting

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing whitespace
      - id: end-of-file-fixer
        name: end of file fixer
      - id: check-added-large-files
        name: check added large files
      - id: check-yaml
        name: check yaml
